Remove extra aarch64 deb package-file line as it breaks pipeline
Error: Failed to upload release asset dnglab_0.7.1-1_arm64.deb. received status code 404